version: 2
updates:
  # Mises à jour des GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  # Mises à jour des dépendances Go
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
